CREATE TABLE `goods` (
  `goods_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '商品ID',
  `dealer_id` int(11) NOT NULL DEFAULT 0 COMMENT '所属渠道商家，一个商家一个模板固定的',
  `dealer_id_desc` varchar(45) NOT NULL DEFAULT '',
  `gdtemp_id` int(11) NOT NULL DEFAULT 0 COMMENT '商品前端模板ID',
  `gdtemp_id_desc` varchar(45) NOT NULL DEFAULT '' COMMENT '商品前端模板描述',
  `category_id` int(5) NOT NULL DEFAULT 0 COMMENT '分类id',
  `category_id_desc` varchar(45) NOT NULL DEFAULT '' COMMENT '分类名称（冗余字段）',
  `brand_id` int(11) NOT NULL DEFAULT 0 COMMENT '品牌ID',
  `brand_id_desc` varchar(50) NOT NULL DEFAULT '' COMMENT '品牌说明',
  `goods_origin_url` varchar(255) NOT NULL DEFAULT '' COMMENT '商品原价外链接',
  `goods_coupon_url` varchar(255) NOT NULL DEFAULT '' COMMENT '商品优惠外链接',
  `goods_type` int(11) NOT NULL DEFAULT 0 COMMENT '商品类型:1虚拟品,2实物',
  `goods_img` varchar(255) NOT NULL DEFAULT '' COMMENT '商品图片',
  `goods_name` varchar(255) NOT NULL DEFAULT '' COMMENT '商品名称',
  `goods_title` varchar(255) NOT NULL DEFAULT '' COMMENT '副标题',
  `goods_desc` mediumtext DEFAULT NULL COMMENT '商品描述(文字)',
  `goods_detail` mediumtext DEFAULT NULL COMMENT '商品详情(图片)',
  `goods_sales` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '商品销量',
  `goods_unit` tinyint(5) NOT NULL DEFAULT 1 COMMENT '商品单位：1件、2台、3个、4套、5盒',
  `stock` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '库存数量',
  `created_at` int(11) NOT NULL DEFAULT 0 COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT 0 COMMENT '更新时间',
  `start_at` int(11) NOT NULL DEFAULT 0 COMMENT '开始时间',
  `end_at` int(11) NOT NULL DEFAULT 0 COMMENT '结束时间',
  `status` tinyint(3) NOT NULL DEFAULT 0 COMMENT '商品状态:1待审核,2审核通过,3审核拒绝,4已上线,5已下线,6已删除',
  `price_exchange_type` tinyint(3) NOT NULL DEFAULT 0 COMMENT '积分兑换类型:1全积分兑换,2积分加现金兑换',
  `price_cost` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '成本价,此商品的成本',
  `price_origin` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '原价,市场价',
  `price_promotion` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '促销价,实际价格',
  `price_coupon` int(10) NOT NULL DEFAULT 0 COMMENT '优惠金额,便宜了多少钱',
  `price_point` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '需要积分数量',
  `price_freight` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '运费价格',
  `union_goods_id` varchar(50) NOT NULL DEFAULT '' COMMENT '第三方商品ID',
  `is_self` tinyint(3) NOT NULL DEFAULT 2 COMMENT '是否是自营:1是,2不是',
  `buynum_min` int(11) NOT NULL DEFAULT 0 COMMENT '最低购买数量',
  `buynum_max` int(11) NOT NULL DEFAULT 0 COMMENT '最多购买数量',
  PRIMARY KEY (`goods_id`),
  KEY `union_goods_id_INDEX` (`union_goods_id`),
  KEY `goods_id_INDEX` (`goods_id`),
  KEY `status_INDEX` (`status`),
  KEY `category_id_INDEX` (`category_id`),
  KEY `expired_at` (`end_at`) USING HASH
) ENGINE=InnoDB AUTO_INCREMENT=154632 DEFAULT CHARSET=utf8mb4 COMMENT='商品表'
