CREATE TABLE `orders` (
  `order_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `order_no` varchar(45) NOT NULL DEFAULT '' COMMENT '订单号',
  `uid` bigint(20) NOT NULL DEFAULT 0 COMMENT '用户UID',
  `app_id` smallint(5) NOT NULL DEFAULT 0 COMMENT '合作方ID',
  `dealer_id` int(11) NOT NULL DEFAULT 0 COMMENT '渠道商ID',
  `gdtemp_id` int(11) DEFAULT 0 COMMENT '商品模板ID',
  `is_self` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否自营:1自营,2非自营',
  `goods_id` int(11) NOT NULL DEFAULT 0 COMMENT '商品ID',
  `union_goods_id` varchar(50) NOT NULL DEFAULT '' COMMENT '第三方商品ID',
  `goods_type` int(11) NOT NULL DEFAULT 0 COMMENT '商品类型',
  `goods_name` varchar(255) NOT NULL DEFAULT '' COMMENT '商品名称',
  `goods_img` varchar(200) NOT NULL DEFAULT '' COMMENT '图片地址',
  `goods_coupon_url` varchar(200) NOT NULL DEFAULT '' COMMENT '商品优惠券地址',
  `goods_num` int(11) NOT NULL DEFAULT 0 COMMENT '商品数量',
  `price_exchange_type` tinyint(3) NOT NULL DEFAULT 0 COMMENT '积分兑换类型:1全积分兑换,2积分加现金兑换',
  `price_origin` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '商品原价',
  `price_promotion` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '优惠价',
  `price_point` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '所需积分',
  `price_freight` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '运费价格',
  `status` tinyint(4) unsigned NOT NULL DEFAULT 0 COMMENT '订单状态:1订单完成,2待付款,3订单关闭,4待发货,5待收货,6退货中',
  `coupon_expired` int(11) unsigned NOT NULL DEFAULT 1 COMMENT '过期时间戳',
  `created_at` int(11) NOT NULL DEFAULT 0 COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT 0 COMMENT '更新时间',
  `chain_req_at` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '上链请求时间',
  `chain_resp_at` int(10) unsigned NOT NULL DEFAULT 0 COMMENT '上链响应时间',
  `chain_resp_msg` varchar(200) NOT NULL DEFAULT '' COMMENT '上链响应失败原因',
  `amount_point` decimal(10,2) NOT NULL DEFAULT 0.00,
  `amount_promotion` decimal(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `order_UNIQUE` (`order_no`),
  KEY `uid_INDEX` (`uid`),
  KEY `goodsid_INDEX` (`goods_id`),
  KEY `gdtemp_id_INDEX` (`gdtemp_id`),
  KEY `is_self_INDEX` (`is_self`)
) ENGINE=InnoDB AUTO_INCREMENT=13571 DEFAULT CHARSET=utf8mb4 COMMENT='订单表'
